### ISSUE TITLE
依赖版本错误

### ISSUE THREAD

**Issue by duffiye** [xuperchain/xasset-sdk-go#15]
TestGetStoken 失败

应该是版本依赖过低

Running tool: /usr/local/go/bin/go test -timeout 30s -run ^TestGetStoken$ github.com/xuperchain/xasset-sdk-go/client/xasset

# github.com/consensys/gurvy/bls377/fr
/Users/manfeiqi/go/pkg/mod/github.com/consensys/gurvy@v0.1.2-0.20200512111154-1662e289e29b/bls377/fr/element.go:517:2: undefined: fromMontElement
/Users/manfeiqi/go/pkg/mod/github.com/consensys/gurvy@v0.1.2-0.20200512111154-1662e289e29b/bls377/fr/element.go:530:2: undefined: mulAssignElement
# github.com/consensys/gurvy/bn256/fr
/Users/manfeiqi/go/pkg/mod/github.com/consensys/gurvy@v0.1.2-0.20200512111154-1662e289e29b/bn256/fr/element.go:517:2: undefined: fromMontElement
/Users/manfeiqi/go/pkg/mod/github.com/consensys/gurvy@v0.1.2-0.20200512111154-1662e289e29b/bn256/fr/element.go:530:2: undefined: mulAssignElement
# github.com/consensys/gurvy/bls381/fr
/Users/manfeiqi/go/pkg/mod/github.com/consensys/gurvy@v0.1.2-0.20200512111154-1662e289e29b/bls381/fr/element.go:517:2: undefined: fromMontElement
/Users/manfeiqi/go/pkg/mod/github.com/consensys/gurvy@v0.1.2-0.20200512111154-1662e289e29b/bls381/fr/element.go:530:2: undefined: mulAssignElement
# github.com/consensys/gurvy/bn256/fp
/Users/manfeiqi/go/pkg/mod/github.com/consensys/gurvy@v0.1.2-0.20200512111154-1662e289e29b/bn256/fp/element.go:517:2: undefined: fromMontElement
/Users/manfeiqi/go/pkg/mod/github.com/consensys/gurvy@v0.1.2-0.20200512111154-1662e289e29b/bn256/fp/element.go:530:2: undefined: mulAssignElement
FAIL	github.com/xuperchain/xasset-sdk-go/client/xasset [build failed]

**Comment by wellzm** [comment]
arm机器上编译的吗？我们更新了crypto包的依赖，辛苦再试一下。
